# Generated by Django 3.2.3 on 2021-08-13 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_galleryimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='name',
        ),
    ]
