# Generated by Django 3.2.3 on 2021-08-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_remove_galleryimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
