# Generated by Django 3.2.3 on 2021-07-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_kompetisi_peserta'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='peserta',
            unique_together={('nama', 'npm')},
        ),
    ]
