# Generated by Django 3.2.3 on 2021-07-29 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_peserta_kompetisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peserta',
            name='kompetisi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peserta', to='dashboard.kompetisi'),
        ),
    ]
