# Generated by Django 3.2.3 on 2021-08-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_peserta_kompetisi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peserta',
            name='npm',
        ),
        migrations.AddField(
            model_name='peserta',
            name='angkatan',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='fakultas',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='is_ketua',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='jurusan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='line_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='no_hp',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
