# Generated by Django 3.2.3 on 2021-08-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_metadatafakultas_makara'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipeKompetisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(max_length=20)),
            ],
        ),
    ]
