# Generated by Django 3.2.3 on 2021-08-14 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_tipekompetisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kompetisi',
            name='tipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kompetisi', to='dashboard.tipekompetisi'),
        ),
    ]
