# Generated by Django 3.2.3 on 2021-08-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20210815_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kompetisi',
            name='kapasitas_kelompok',
            field=models.IntegerField(blank=True),
        ),
    ]
