# Generated by Django 3.2.3 on 2021-08-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_kompetisi_kapasitas_kelompok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kompetisi',
            name='kapasitas_kelompok',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
