# Generated by Django 3.2.3 on 2021-08-14 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_kompetisi_kapasitas_kelompok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peserta',
            name='file_cv',
        ),
        migrations.RemoveField(
            model_name='peserta',
            name='is_ketua',
        ),
        migrations.AlterField(
            model_name='peserta',
            name='foto_ktm',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='screenshot_siak',
            field=models.ImageField(upload_to=''),
        ),
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('fakultas', models.CharField(max_length=50)),
                ('jurusan', models.CharField(max_length=50)),
                ('angkatan', models.CharField(max_length=4)),
                ('no_hp', models.CharField(max_length=15)),
                ('line_id', models.CharField(max_length=30)),
                ('is_ketua', models.BooleanField(blank=True, null=True)),
                ('foto_ktm', models.ImageField(upload_to='')),
                ('screenshot_siak', models.ImageField(upload_to='')),
                ('file_cv', models.FileField(blank=True, null=True, upload_to='')),
                ('kelompok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anggota', to='dashboard.kelompok')),
            ],
        ),
    ]
