# Generated by Django 3.2.3 on 2021-08-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20210815_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='KompetisiKTIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_pendaftaran', models.DateField()),
            ],
        ),
    ]
