# Generated by Django 3.2.3 on 2021-08-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_kompetisiktia'),
    ]

    operations = [
        migrations.AddField(
            model_name='kompetisiktia',
            name='judul',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
