# Generated by Django 3.2.3 on 2021-08-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_kompetisiktia_judul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kompetisiktia',
            name='judul',
            field=models.CharField(max_length=100),
        ),
    ]
