# Generated by Django 3.2.3 on 2021-08-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_kompetisiktia_judul'),
    ]

    operations = [
        migrations.AddField(
            model_name='kompetisi',
            name='tanggal_pendaftaran',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='kompetisiktia',
            name='tanggal_pendaftaran',
            field=models.DateField(null=True),
        ),
    ]
