# Generated by Django 3.2.3 on 2021-08-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20210822_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kompetisi',
            name='tanggal_pendaftaran',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='kompetisiktia',
            name='tanggal_pendaftaran',
            field=models.DateField(),
        ),
    ]
