# Generated by Django 3.2.3 on 2021-07-16 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lomba', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('guidebook_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mentor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeline', models.DateField()),
                ('deskripsi', models.CharField(max_length=100)),
                ('nama_lomba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lomba.lomba')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingLearnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learnt', models.TextField()),
                ('nama_lomba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lomba.lomba')),
            ],
        ),
        migrations.CreateModel(
            name='LombaRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField()),
                ('nama_lomba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lomba.lomba')),
            ],
        ),
        migrations.AddField(
            model_name='lomba',
            name='nama_mentor',
            field=models.ManyToManyField(to='lomba.Mentor'),
        ),
    ]
