# Generated by Django 3.2.3 on 2021-08-19 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lomba', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_url', models.TextField(blank=True, default='https://images.unsplash.com/photo-1519818187420-8e49de7adeef', null=True)),
                ('about', models.TextField()),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('guidebook_link', models.CharField(default='#', max_length=200)),
                ('custom_timeline', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mentor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('active', models.BooleanField(blank=True, default=False, null=True)),
                ('deskripsi', models.CharField(max_length=100)),
                ('nama_lomba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lomba.lomba')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingLearnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learnt', models.TextField()),
                ('nama_lomba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lomba.lomba')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.TextField()),
                ('nama_lomba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lomba.lomba')),
            ],
        ),
        migrations.CreateModel(
            name='LombaRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField()),
                ('nama_lomba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lomba.lomba')),
            ],
        ),
        migrations.AddField(
            model_name='lomba',
            name='nama_mentor',
            field=models.ManyToManyField(blank=True, null=True, to='lomba.Mentor'),
        ),
    ]
