# Generated by Django 3.2.3 on 2021-07-14 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lomba', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lomba',
            old_name='name',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='lombadetail',
            old_name='name',
            new_name='namaLomba',
        ),
        migrations.RenameField(
            model_name='lombatimeline',
            old_name='lomba',
            new_name='namaLomba',
        ),
    ]
