# Generated by Django 3.2.3 on 2021-07-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lomba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lomba',
            name='image_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
