# Generated by Django 3.2.3 on 2021-07-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lomba', '0002_lomba_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lomba',
            name='alias',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
