# Generated by Django 3.2.3 on 2021-07-14 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lomba', '0002_auto_20210714_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lombadetail',
            old_name='namaLomba',
            new_name='lomba',
        ),
        migrations.RenameField(
            model_name='lombatimeline',
            old_name='namaLomba',
            new_name='lombaDetail',
        ),
    ]
