# Generated by Django 3.2.3 on 2021-08-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lomba', '0003_alter_lomba_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lomba',
            name='custom_timeline',
            field=models.BooleanField(default=False),
        ),
    ]
