# Generated by Django 3.2.3 on 2021-07-15 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lomba', '0004_auto_20210715_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lombatimeline',
            old_name='lomba',
            new_name='namaLomba',
        ),
    ]
