# Generated by Django 3.2.3 on 2021-07-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lomba', '0006_auto_20210715_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mentor', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='lomba',
            old_name='nama',
            new_name='nama_lomba',
        ),
        migrations.DeleteModel(
            name='LombaMentor',
        ),
    ]
