# Generated by Django 3.2.3 on 2021-07-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lomba', '0007_auto_20210716_0302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lombalearned',
            old_name='namaLomba',
            new_name='lomba',
        ),
        migrations.RenameField(
            model_name='lombarules',
            old_name='namaLomba',
            new_name='lomba',
        ),
        migrations.RenameField(
            model_name='lombatimeline',
            old_name='namaLomba',
            new_name='lomba',
        ),
        migrations.AddField(
            model_name='lomba',
            name='mentor',
            field=models.ManyToManyField(to='lomba.Mentor'),
        ),
    ]
