# Generated by Django 3.2.3 on 2021-07-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestStars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_seminar', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=300)),
                ('subjects', models.TextField()),
                ('d_day', models.DateField()),
                ('is_past', models.BooleanField(default=False)),
                ('guest_stars', models.ManyToManyField(to='seminar.GuestStars')),
            ],
        ),
    ]
