# Generated by Django 3.2.3 on 2021-07-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='seminar_image',
            field=models.ImageField(default='gronru.jpg', upload_to=''),
        ),
    ]
