# Generated by Django 3.2.3 on 2021-07-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='is_past',
            field=models.BooleanField(default=False),
        ),
    ]
