# Generated by Django 3.2.3 on 2021-07-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0002_seminar_seminar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='d_day',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='seminar_image',
            field=models.ImageField(default='1955361.jpg', upload_to=''),
        ),
    ]
