# Generated by Django 3.2.3 on 2021-08-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0003_auto_20210729_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='air_time',
            field=models.DateTimeField(null=True),
        ),
    ]
