# Generated by Django 3.2.3 on 2021-08-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0004_seminar_air_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='air_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
