# Generated by Django 3.2.3 on 2021-08-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0005_alter_seminar_air_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='air_time',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
