# Generated by Django 3.2.3 on 2021-08-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0006_alter_seminar_air_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='gueststars',
            name='biografi',
            field=models.TextField(default='test'),
        ),
    ]
