# Generated by Django 3.2.3 on 2021-08-22 04:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0007_gueststars_biografi'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
