# Generated by Django 3.2.3 on 2021-08-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0008_seminar_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Launching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_seminar', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=300)),
                ('subjects', models.TextField()),
                ('d_day', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('seminar_image', models.ImageField(default='1955361.jpg', upload_to='')),
                ('guest_stars', models.ManyToManyField(to='seminar.GuestStars')),
            ],
        ),
    ]
