# Generated by Django 3.2.3 on 2021-08-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0009_launching'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Launching',
        ),
    ]
